services:
  - type: web
    name: cms-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    healthCheckPath: /api/headings
    autoDeploy: true 