services:
  - type: web
    name: cms-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/app.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    healthCheckPath: /api/headings
    autoDeploy: true 